### PR TITLE
Gulp File Include, Fix URLs

### PR DESCRIPTION
**Pull request by thecodingwizard**
(Finally) A no-conflict PR that fixes URLs and uses gulp file include to include the head, navbar, footer, and scripts. This also contains the changes in [this](https://github.com/valkyrierobotics/valkyrierobotics.com/pull/3/commits/88d6ecc2401115714970e4a3291c1bff8f249c18) PR.

### CODE REVIEW

**Comment by m3rcuriel** [comment]
Um... no... this is now how to do this. I will fix.

**Comment by m3rcuriel** [comment]
Okay, I give up. I can't fix this by hand. Can you just take a clean master, rebranch, and redo these changes? It's because of the index fuckery I did while fixing node_modules/

Also @Amit-Palekar's merge technique.

If it's really too much work, I can probably hack it together...

To explain:

You forked off of the current HEAD. You then made changes. Then, I used index fuckery to remove node_modules, which made changes all the way back to when those were first introduced. As a result, your PR is now insane. Sorry?

**Comment by thecodingwizard** [comment]
Alright.... so you want me to fork master again, then only implement Gulp File Include ([this](https://github.com/valkyrierobotics/valkyrierobotics.com/pull/4/commits/53946a0b925c9ebcd11fd8edbe6c23cd8eb327bb) commit)?

**Comment by thecodingwizard** [comment]
oh and for some reason node_modules and build appeared again...

**Comment by m3rcuriel** [comment]
CRY. Implement whatever commits you want. AFTER I FIX NODE MODULES AGAIN!

**Comment by m3rcuriel** [comment]
Okay. Finally gone.

**Comment by m3rcuriel** [comment]
See Slack

**Pull request closed without merging**
